name: Compile PDFs

on:
  push: {}
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v7

    - name: Install fonts
      run: |
        apt update
        apt install --yes \
          fonts-roboto \
          fonts-adobe-sourcesans3 \
          fonts-hosny-amiri \
          ;

    - name: Compile
      run: |
        make
        xelatex -interaction=nonstopmode -halt-on-error -output-directory=examples examples/languages-arabic.tex
        xelatex -interaction=nonstopmode -halt-on-error -output-directory=examples examples/languages-turkish.tex

    - uses: actions/upload-artifact@v6
      with:
        name: examples
        path: examples/*.pdf
